[package]
name = "stivale"
description = "A crate for parsing stivale and stivale2 structures"
version = "0.2.1"
authors = ["Anhad Singh <andypythonappdeveloper@gmail.com>"]
license = "MIT/Apache-2.0"
edition = "2018"

readme = "README.md"
categories = ["no-std"]

[dependencies]
bitflags = "1.2.1"
